---
title: "script oficial"
output: html_document
---

# Insertar librerías que vamos a usar

```{r}
library(tidyverse)
library(readxl)
library(janitor)
library(dplyr)
library(stringi)
```



# Unas últimas modificaciones antes de hacer las regresiones

```{r}
df_final <- read_csv("data/base_final_lista.csv")

df_final <- df_final |>
  mutate(pleb_2022_bin = ifelse(apruebo > rechazo, 1, 0 ) |> as.factor())

df_final <- df_final |> 
  mutate(pleb_2023_bin = ifelse(a_favor > en_contra, 1, 0) |> as.factor())

df_final <- df_final |> 
  mutate(
    tendencia = case_when(
      pacto %in% c("Chile Vamos", "Unidos Por La Dignidad") ~ "Derecha",
      pacto %in% c("Unidad Por El Apruebo", "Frente Amplio", "Chile Digno Verde Y Soberano", "Dignidad Ahora") ~ "Izquierda",
      pacto == "Independientes" ~ "Independiente",
      TRUE ~ "Otro"
    )
  )
```

# Ahora si regresiones

```{r}
df_final <- df_final |> 
  mutate(tendencia = as.factor(tendencia))

modelo_2022 <- glm(df_final$pleb_2022_bin ~ df_final$escolaridad_promedio_hombres_18_mas + df_final$escolaridad_promedio_mujeres_18_mas + df_final$tendencia + df_final$numero_de_personas_en_situacion_de_pobreza_por_ingresos + df_final$grupo_edad_unido,
                   data = df_final,
                   family = binomial(link = "logit"))
```

```{r}
modelo_2023 <- glm(df_final$pleb_2023_bin ~ df_final$escolaridad_promedio_hombres_18_mas + df_final$escolaridad_promedio_mujeres_18_mas + df_final$tendencia + df_final$porcentaje_de_personas_en_situacion_de_pobreza_por_ingresos_2022 + df_final$grupo_edad_unido,
                   data = df_final,
                   family = binomial(link = "logit"))
```

# Resumen de los modelos

```{r}
summary(modelo_2022)

summary(modelo_2023)

```

# Códigos para gráficar mapa

```{r}
cut_data <- read_xls("input/CUT_2018_v04.xls") |> 
  clean_names() |> 
  select(codigo_comuna_2018, nombre_comuna) |> 
  rename(comuna = nombre_comuna) |> 
  mutate(comuna = stri_trans_general(comuna, "Latin-ASCII")) |> 
  mutate(
    comuna = case_when(
      comuna == "Paiguano" ~ "Paihuano",
      comuna == "Llay-Llay" ~ "Llay Llay",
      comuna == "Marchigue" ~ "Marchihue",
      comuna == "Cabo de Hornos" ~ "Cabo de Hornos(Ex-Navarino)",
      comuna == "San Pedro de La paz" ~ "San Pedro de la paz",
      comuna == "San Juan de La Costa" ~ "San Juan de la Costa",
      comuna == "O'higgins" ~ "O'Higgins",
      comuna == "Treguaco" ~ "Trehuaco",
      TRUE ~ comuna
    )
  )
  
df_final <- df_final |> 
  left_join(cut_data, by = "comuna")
```

